name: Build and Deploy

on:
  push:
    branches:
      - main
      - deploy
  pull_request:
    branches:
      - main
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Build Website
        run: yarn build
